apiVersion: v1
kind: Service
metadata:
  name: llama-inference-service
spec:
  selector:
    app: llama-inference
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
